services:
  client:
    build: 
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      server:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
  server:
    build: 
      context: ./server
    ports:
      - "8558:8558"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:8558/system/health"]
      interval: 10s
      timeout: 150s
      retries: 10
