name: Test Demo

on:
  push:
    branches: 
      - main
    paths: 
       - demo/**

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version-file: demo/server/go.mod
          cache: true

      - name: Run Server Tests
        run: go test ./demo/server/... -shuffle=on -race
