name: Pipeline

on:
  push:
    branches: 
      - main
    
jobs:
  test:
    uses: mastrasec/vectoria/.github/workflows/test.yaml@main
  
  spdx:
    uses: mastrasec/vectoria/.github/workflows/spdx.yaml@main
